### ISSUE TITLE
Separate/Combine doesn't work on loop 

### ISSUE THREAD

**Issue by mikerodd** [Secrop/ShaderNodesExtra#2]
Separate and combine xyz coordinate on a vector doesn't seem to work. Here an example with a brick texture and the itorator connected to the scale : 

![image](https://user-images.githubusercontent.com/4293086/37258946-e778764a-257f-11e8-8dac-96be1d24bb68.png)

when I separate combine coordinates, the loop node  is not working  : 
![image](https://user-images.githubusercontent.com/4293086/37258965-31cca43c-2580-11e8-8850-48db0cd6387f.png)
...And thanks for this add-on, it seems very promising !

**Comment by Secrop** [comment]
Could you attach a file with the nodegroup? Your screenshots don't show the complete nodetree and the outputs are important for the Loop Node as they are tightly connected to the Inputs. (from what I can see, you need to add a vector output to the nodegroup output, and connect the Vector input with the Vector output. This way we enforce that each step will recieve the vector.. otherwise only the first loop will be able to use the vector)

**Comment by mikerodd** [comment]
Yes it works with a vector as an input/output parameter :-)
